/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gacoan_SistemNotifikasi */

#ifndef _Included_gacoan_SistemNotifikasi
#define _Included_gacoan_SistemNotifikasi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gacoan_SistemNotifikasi
 * Method:    panggilAntrean
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gacoan_SistemNotifikasi_panggilAntrean
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
