/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gacoan_GacoanEngine */

#ifndef _Included_gacoan_GacoanEngine
#define _Included_gacoan_GacoanEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gacoan_GacoanEngine
 * Method:    hitungNota
 * Signature: (Lgacoan/TransaksiPesanan;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gacoan_GacoanEngine_hitungNota
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
